# Eclipse Mosquitto 글로벌 인프라 설정 파일
# [FRS-12.1] 1883 기본 포트 개방 및 모든 네트워크 인터페이스 바인딩
listener 1883 0.0.0.0

# [샌드박스 검증용] 인증서 없는 익명 자격 증명 임시 허용
allow_anonymous true

# 데이터 및 로그 영구 박제 아카이빙 경로 지정
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log